version: '3.8'

services:
  todo:
    build:
      context: ./app_todo
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  order:
    build:
      context: ./app_order
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
